# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: Check code style
      run: |
        # black will check if there are syntax errors
        # or code without predef formatting
        black . --check
    - name: Lint with bandit
      run: |
        # bandit will check for security issues
        bandit -c .bandit -r .
    - name: Test with pytest
      run: |
        # prepend with `python -m` so cwd is added to sys.path
        # and our modules are made available to the tests
        python -m pytest
